version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:4200" # Adjust this according to your app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - LUCIDCHART_API_KEY=${LUCIDCHART_API_KEY}
    depends_on:
      - threat-engine

  threat-engine:
    build:
      context: ./threat-engine
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

