version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  threat-engine:
    build:
      context: .
      dockerfile: threat-engine/Dockerfile.threat-engine
    ports:
      - "8000:8000"
    depends_on:
      - backend